services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3030:80"
    depends_on:
      - db
    environment:
      NODE_ENV: development
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: apiresultsuser
      DB_PASSWORD: apiresultspwd
      DB_NAME: cesi_live_quizz
    volumes:
      # Mount entire project directory for live reload
      - .:/app
      # Exclude node_modules to avoid conflicts
      - /app/node_modules

  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: apiresultsrootpwd
      MYSQL_DATABASE: cesi_live_quizz
      MYSQL_USER: apiresultsuser
      MYSQL_PASSWORD: apiresultspwd
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  adminer:
    image: adminer:latest
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_DB_DRIVER: mysql
      ADMINER_DEFAULT_DB_HOST: db
      ADMINER_DEFAULT_DB_PORT: 3306
      ADMINER_DEFAULT_DB_USERNAME: apiresultsuser
      ADMINER_DEFAULT_DB_PASSWORD: apiresultspwd
      ADMINER_DEFAULT_DB_NAME: cesi_live_quizz
    depends_on:
      - db

volumes:
  db_data: {}
